### ISSUE TITLE
What happened with release/foxy/ament_nodl branch?

### ISSUE THREAD

**Issue by shr-project** [ros2-gbp/ament_nodl-release#1]
release/foxy/ament_nodl/0.1.0-1 tag (6aaf56d0aa827ff07cfd26fcb39c052050ca9a57) exists in
release/rolling/ament_nodl branch, but there is no release/foxy/ament_nodl branch, causing following error in meta-ros builds:

```
WARNING: ament-nodl-0.1.0-1-r0 do_fetch: Failed to fetch URL git://github.com/ros2-gbp/ament_nodl-release;branch=release/foxy/ament_nodl;protocol=https, attempting MIRRORS if available
ERROR: ament-nodl-0.1.0-1-r0 do_fetch: Fetcher failure: Unable to find revision 6aaf56d0aa827ff07cfd26fcb39c052050ca9a57 in branch release/foxy/ament_nodl even from upstream
ERROR: ament-nodl-0.1.0-1-r0 do_fetch: Fetcher failure for URL: 'git://github.com/ros2-gbp/ament_nodl-release;branch=release/foxy/ament_nodl;protocol=https'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ros/webos-foxy-dunfell/tmp-glibc/work/qemux86-webos-linux/ament-nodl/0.1.0-1-r0/temp/log.do_fetch.45308
ERROR: Task (/jenkins/mjansa/build/ros/webos-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ament-nodl/ament-nodl_0.1.0-1.bb:do_fetch) failed with exit code '1'
```

I'll add an work around in meta-ros for this, but it's maybe a 6th ROS component where the branch doesn't exist or was deleted, what's going on?

**Comment by kyrofa** [comment]
Huh you're right, I have no idea what happened. Maybe it was lost in the migration to ros2-gbp (this release repo used to be elsewhere). I'll get it out ASAP, thanks for the heads up!

**Comment by kyrofa** [comment]
This should be solved now, can you confirm?

**Comment by shr-project** [comment]
Looks good to me

```
Fetching origin
From https://github.com/ros2-gbp/ament_nodl-release
 * [new branch]      debian/foxy/ament_nodl               -> debian/foxy/ament_nodl
 * [new branch]      debian/foxy/focal/ament_nodl         -> debian/foxy/focal/ament_nodl
 * [new branch]      patches/debian/foxy/ament_nodl       -> patches/debian/foxy/ament_nodl
 * [new branch]      patches/debian/foxy/focal/ament_nodl -> patches/debian/foxy/focal/ament_nodl
 * [new branch]      patches/release/foxy/ament_nodl      -> patches/release/foxy/ament_nodl
 * [new branch]      release/foxy/ament_nodl              -> release/foxy/ament_nodl
```

```
git branch -a --contains 6aaf56d0aa827ff07cfd26fcb39c052050ca9a57
  debian/foxy/ament_nodl
  debian/foxy/focal/ament_nodl
  debian/rolling/ament_nodl
  debian/rolling/focal/ament_nodl
  release/foxy/ament_nodl
  release/rolling/ament_nodl
```

Will drop the work around now, thanks for very fast resolution!

**Comment by kyrofa** [comment]
My pleasure, thank you again. I'm willing to bet the other component issues are due to an incomplete migration as well.

**Comment by shr-project** [comment]
I have no experience with bloom, so not sure what "incomplete migration" is in this context, let me link the other issues I've reported recently to link them all together with this resolved one :).

https://github.com/ros2-gbp/ros2_intel_realsense-release/issues/1
https://github.com/ros2-gbp/osrf_testings_tools_cpp-release/issues/2
https://github.com/ros2-gbp/robot_state_publisher-release/issues/2
